CREATE TABLE IF NOT EXISTS pay_register (
    employee_id INT,
    employee_code TEXT,
    month TEXT,
    emonth TEXT,
    eyear INT,
    code_wday TEXT,
    actdays FLOAT,
    arrdays FLOAT,
    total_paid_days FLOAT,
    leavenchdays FLOAT,
    notpaydays FLOAT,
    notdeddays FLOAT,
    ot_hrs FLOAT,
    basic FLOAT,
    h_r_a FLOAT,
    lta FLOAT,
    gratuity FLOAT,
    leave_encash FLOAT,
    mange_allow FLOAT,
    bonus FLOAT,
    other_allowance FLOAT,
    yearly_bonus FLOAT,
    incentive FLOAT,
    night_shift_all FLOAT,
    sign_tenure_bon FLOAT,
    nontax FLOAT,
    referal_bonus FLOAT,
    notice_per_pay FLOAT,
    misc_earn FLOAT,
    salary_advance FLOAT,
    tele_reimb FLOAT,
    joibon FLOAT,
    serweigh FLOAT,
    relocation FLOAT,
    prof_developmnt FLOAT,
    maternity_bonus FLOAT,
    gross_earning FLOAT,
    pt_ded FLOAT,
    pf_ded FLOAT,
    esi_employee_ded FLOAT,
    vpf_ded FLOAT,
    l_w_f_ded FLOAT,
    sal_adv_ded FLOAT,
    notice_per_ded_ded FLOAT,
    medical_ins_par_ded FLOAT,
    oth_dedu_ded FLOAT,
    other_ded_2_ded FLOAT,
    gross_deduction FLOAT,
    total_netpay FLOAT,
    income_tax_ded FLOAT,
    lopd FLOAT,
    remark TEXT,
    PRIMARY KEY (employee_id, month, eyear)
);

CREATE TABLE IF NOT EXISTS tax_data (
    employee_id INT,
    month TEXT,
    eyear INT,
    total_tax_liability FLOAT,
    PRIMARY KEY (employee_id, month, eyear)
);

CREATE TABLE IF NOT EXISTS lop_data (
    employee_id INT,
    employee_code TEXT,
    consultant_name TEXT,
    lop_date DATE,
    lop_days FLOAT,
    month TEXT
);

CREATE TABLE IF NOT EXISTS ot_data (
    employee_id INT,
    employee_code TEXT,
    allowance_type TEXT,
    from_date DATE,
    to_date DATE,
    component_in_pay_slip TEXT,
    paid_amount FLOAT,
    month TEXT
);